stages:
  prepare:
    cmd: python prepare/prepare.py
    deps:
    - prepare/prepare.py
    outs:
    - prepare/X_full.csv
    - prepare/y_full.csv
    - prepare/X_train.csv
    - prepare/y_train.csv
    - prepare/X_val.csv
    - prepare/y_val.csv
  train_linear:
    cmd: \
  validate_linear:
    cmd: ^
  train_tree:
    cmd: python train_tree.py
    deps:
    - prepare/X_train.csv
    - prepare/y_train.csv
    - train_tree.py
    outs:
    - models/tree_model.joblib
  validate_tree:
    cmd: python validate_tree.py
    deps:
    - models/tree_model.joblib
    - prepare/X_val.csv
    - prepare/y_val.csv
    - validate_tree.py
    outs:
    - models/tree_metrics.json
    - models/tree_structure.png
    - models/tree_structure_full.png
  train_cat:
    cmd: python train_cat.py
    deps:
    - prepare/X_train.csv
    - prepare/y_train.csv
    - train_cat.py
    outs:
    - models/cat_model.cbm
  validate_cat:
    cmd: python validate_cat.py
    deps:
    - models/cat_model.cbm
    - prepare/X_val.csv
    - prepare/y_val.csv
    - validate_cat.py
    outs:
    - models/cat_feature_importance.png
    - models/cat_feature_importance_full.png
    - models/cat_metrics.json
