stages:
  prepare:
    cmd: python prepare/prepare.py
    deps:
      - prepare/prepare.py
    outs:
      - prepare/X_full.csv
      - prepare/y_full.csv
      - prepare/X_train.csv
      - prepare/y_train.csv
      - prepare/X_val.csv
      - prepare/y_val.csv

  train_linear:
    cmd: python train_linear.py
    deps:
      - prepare/X_train.csv
      - prepare/y_train.csv
      - train_linear.py
    outs:
      - models/linear_model.joblib

  validate_linear:
    cmd: python validate_linear.py
    deps:
      - models/linear_model.joblib
      - prepare/X_val.csv
      - prepare/y_val.csv
      - validate_linear.py
    outs:
      - models/linear_metrics.json
      - models/residual_linear.png
      - models/pred_vs_actual_linear.png

  train_tree:
    cmd: python train_tree.py
    deps:
      - prepare/X_train.csv
      - prepare/y_train.csv
      - train_tree.py
    outs:
      - models/tree_model.joblib

  validate_tree:
    cmd: python validate_tree.py
    deps:
      - models/tree_model.joblib
      - prepare/X_val.csv
      - prepare/y_val.csv
      - validate_tree.py
    outs:
      - models/tree_metrics.json
      - models/tree_structure.png
      - models/tree_structure_full.png

  train_cat:
    cmd: python train_cat.py
    deps:
      - prepare/X_train.csv
      - prepare/y_train.csv
      - train_cat.py
    outs:
      - models/cat_model.cbm

  validate_cat:
    cmd: python validate_cat.py
    deps:
      - models/cat_model.cbm
      - prepare/X_val.csv
      - prepare/y_val.csv
      - validate_cat.py
    outs:
      - models/cat_feature_importance.png
      - models/cat_feature_importance_full.png
      - models/cat_metrics.json

  train_xgb:
    cmd: python train_xgb.py
    deps:
      - prepare/X_train.csv
      - prepare/y_train.csv
      - train_xgb.py
    outs:
      - models/xgb_model.json

  validate_xgb:
    cmd: python validate_xgb.py
    deps:
      - models/xgb_model.json
      - prepare/X_val.csv
      - prepare/y_val.csv
      - validate_xgb.py
    outs:
      - models/xgb_feature_importance.png
      - models/xgb_feature_importance_full.png
      - models/xgb_metrics.json

  train_mlp:
    cmd: python train_mlp.py
    deps:
      - prepare/X_train.csv
      - prepare/y_train.csv
      - train_mlp.py
    outs:
      - models/mlp_model.joblib
      - models/mlp_loss_curve.png
      - models/mlp_weight_hist.png
      - runs/mlp/

  validate_mlp:
    cmd: python validate_mlp.py
    deps:
      - models/mlp_model.joblib
      - prepare/X_val.csv
      - prepare/y_val.csv
      - validate_mlp.py
    outs:
      - models/mlp_metrics.json

  fullrun_linear:
    cmd: python fullrun_linear.py
    deps:
      - prepare/X_full.csv
      - prepare/y_full.csv
      - fullrun_linear.py
    outs:
      - models/linear_model_full.joblib
      - models/residual_linear_full.png
      - models/pred_vs_actual_linear_full.png

  fullrun_tree:
    cmd: python fullrun_tree.py
    deps:
      - prepare/X_full.csv
      - prepare/y_full.csv
      - fullrun_tree.py
    outs:
      - models/tree_model_full.joblib
      - models/tree_structure_full_full.png

  fullrun_cat:
    cmd: python fullrun_cat.py
    deps:
      - prepare/X_full.csv
      - prepare/y_full.csv
      - fullrun_cat.py
    outs:
      - models/cat_model_full.cbm
      - models/cat_feature_importance_full_full.png

  fullrun_xgb:
    cmd: python fullrun_xgb.py
    deps:
      - prepare/X_full.csv
      - prepare/y_full.csv
      - fullrun_xgb.py
    outs:
      - models/xgb_model_full.json
      - models/xgb_feature_importance_full_full.png

  fullrun_mlp:
    cmd: python fullrun_mlp.py
    deps:
      - prepare/X_full.csv
      - prepare/y_full.csv
      - fullrun_mlp.py
    outs:
      - models/mlp_model_full.joblib
      - models/mlp_loss_curve_full.png
