tree:
  max_depth: 5
  random_state: 42
cat:
  depth: 4
  learning_rate: 0.1
  iterations: 500
  random_state: 42
xgb:
  max_depth: 4
  learning_rate: 0.1
  n_estimators: 300
  random_state: 42
mlp:
  hidden_layer_sizes: [64, 32]
  activation: relu
  solver: adam
  max_iter: 1000
  random_state: 42

